In [34]:
import pandas as pd

In [35]:
csv = pd.read_excel("datas/Statistical Tables on June 2025 CPI for All Income Households.xlsx")

In [36]:
table_18 = pd.read_excel("datas/Statistical Tables on June 2025 CPI for All Income Households.xlsx", sheet_name="table 18", skiprows=2)

table_18.head()

,(2018=100),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jan,NaN,Feb,NaN,Mar,NaN,Apr,NaN,May,...,NaN,Sep,NaN,Oct,NaN,Nov,NaN,Dec,NaN,Ave
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1994,3.09,NaN,3.05,NaN,3.06,NaN,3.05,NaN,3.03,...,NaN,2.97,NaN,2.97,NaN,2.97,NaN,2.96,NaN,3.01

In [37]:
# Save table_18 DataFrame to a CSV file
table_18.to_csv("table_18.csv", index=False)

In [38]:
table_18

,(2018=100),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jan,NaN,Feb,NaN,Mar,NaN,Apr,NaN,May,...,NaN,Sep,NaN,Oct,NaN,Nov,NaN,Dec,NaN,Ave
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1994,3.09,NaN,3.05,NaN,3.06,NaN,3.05,NaN,3.03,...,NaN,2.97,NaN,2.97,NaN,2.97,NaN,2.96,NaN,3.01
5,1995,2.91,NaN,2.89,NaN,2.88,NaN,2.87,NaN,2.86,...,NaN,2.75,NaN,2.74,NaN,2.74,NaN,2.74,NaN,2.82
6,1996,2.66,NaN,2.64,NaN,2.64,NaN,2.63,NaN,2.62,...,NaN,2.58,NaN,2.57,NaN,2.57,NaN,2.55,NaN,2.6
7,1997,2.52,NaN,2.51,NaN,2.5,NaN,2.5,NaN,2.49,...,NaN,2.44,NaN,2.43,NaN,2.41,NaN,2.4,NaN,2.46
8,1998,2.37,NaN,2.33,NaN,2.31,NaN,2.3,NaN,2.27,...,NaN,2.21,NaN,2.21,NaN,2.18,NaN,2.18,NaN,2.25
9,1999,2.14,NaN,2.13,NaN,2.14,NaN,2.14,NaN,2.14,...,NaN,2.11,NaN,2.1,NaN,2.1,NaN,2.1,NaN,2.12
10,2000,2.03,NaN,2.02,NaN,2.02,NaN,2.02,NaN,2.01,...,NaN,1.98,NaN,1.97,NaN,1.94,NaN,1.93,NaN,1.99
11,2001,1.91,NaN,1.91,NaN,1.91,NaN,1.91,NaN,1.91,...,NaN,1.87,NaN,1.87,NaN,1.87,NaN,1.86,NaN,1.89
12,2002,1.85,NaN,1.86,NaN,1.85,NaN,1.85,NaN,1.85,...,NaN,1.83,NaN,1.83,NaN,1.83,NaN,1.82,NaN,1.84
13,2003,1.82,NaN,1.81,NaN,1.81,NaN,1.81,NaN,1.81,...,NaN,1.79,NaN,1.79,NaN,1.78,NaN,1.78,NaN,1.8
14,2004,1.77,NaN,1.76,NaN,1.76,NaN,1.75,NaN,1.74,...,NaN,1.68,NaN,1.68,NaN,1.67,NaN,1.66,NaN,1.72
15,2005,1.65,NaN,1.64,NaN,1.64,NaN,1.63,NaN,1.63,...,NaN,1.59,NaN,1.58,NaN,1.57,NaN,1.57,NaN,1.61
16,2006,1.56,NaN,1.54,NaN,1.54,NaN,1.54,NaN,1.53,...,NaN,1.52,NaN,1.51,NaN,1.51,NaN,1.51,NaN,1.53
17,2007,1.5,NaN,1.5,NaN,1.5,NaN,1.5,NaN,1.49,...,NaN,1.47,NaN,1.47,NaN,1.46,NaN,1.45,NaN,1.48
18,2008,1.43,NaN,1.43,NaN,1.42,NaN,1.4,NaN,1.38,...,NaN,1.34,NaN,1.34,NaN,1.34,NaN,1.35,NaN,1.37
19,2009,1.34,NaN,1.33,NaN,1.33,NaN,1.32,NaN,1.32,...,NaN,1.31,NaN,1.3,NaN,1.3,NaN,1.29,NaN,1.31
20,2010,1.29,NaN,1.28,NaN,1.28,NaN,1.27,NaN,1.27,...,NaN,1.26,NaN,1.26,NaN,1.25,NaN,1.25,NaN,1.27
21,2011,1.24,NaN,1.22,NaN,1.22,NaN,1.22,NaN,1.21,...,NaN,1.2,NaN,1.2,NaN,1.19,NaN,1.2,NaN,1.21
22,2012,1.19,NaN,1.19,NaN,1.19,NaN,1.18,NaN,1.18,...,NaN,1.16,NaN,1.16,NaN,1.16,NaN,1.16,NaN,1.17
23,2013,1.16,NaN,1.15,NaN,1.15,NaN,1.15,NaN,1.15,...,NaN,1.14,NaN,1.13,NaN,1.13,NaN,1.12,NaN,1.14
24,2014,1.12,NaN,1.11,NaN,1.12,NaN,1.11,NaN,1.11,...,NaN,1.09,NaN,1.09,NaN,1.1,NaN,1.1,NaN,1.1
25,2015,1.1,NaN,1.1,NaN,1.1,NaN,1.1,NaN,1.1,...,NaN,1.1,NaN,1.1,NaN,1.09,NaN,1.09,NaN,1.1
26,2016,1.09,NaN,1.09,NaN,1.09,NaN,1.09,NaN,1.09,...,NaN,1.08,NaN,1.08,NaN,1.07,NaN,1.07,NaN,1.08
27,2017,1.06,NaN,1.06,NaN,1.06,NaN,1.06,NaN,1.06,...,NaN,1.05,NaN,1.04,NaN,1.04,NaN,1.04,NaN,1.05
28,2018,1.03,NaN,1.02,NaN,1.02,NaN,1.01,NaN,1.01,...,NaN,0.98,NaN,0.98,NaN,0.98,NaN,0.99,NaN,1
29,2019,0.99,NaN,0.98,NaN,0.98,NaN,0.98,NaN,0.98,...,NaN,0.97,NaN,0.97,NaN,0.97,NaN,0.96,NaN,0.98
30,2020,0.96,NaN,0.96,NaN,0.96,NaN,0.96,NaN,0.96,...,NaN,0.95,NaN,0.95,NaN,0.94,NaN,0.93,NaN,0.95
31,2021,0.92,NaN,0.92,NaN,0.92,NaN,0.93,NaN,0.93,...,NaN,0.91,NaN,0.91,NaN,0.91,NaN,0.9,NaN,0.92
32,2022,0.9,NaN,0.89,NaN,0.89,NaN,0.88,NaN,0.88,...,NaN,0.86,NaN,0.85,NaN,0.84,NaN,0.84,NaN,0.87
33,2023,0.82,NaN,0.82,NaN,0.83,NaN,0.83,NaN,0.83,...,NaN,0.81,NaN,0.81,NaN,0.81,NaN,0.81,NaN,0.82
34,2024,0.8,NaN,0.8,NaN,0.8,NaN,0.8,NaN,0.8,...,NaN,0.79,NaN,0.79,NaN,0.79,NaN,0.78,NaN,0.79
35,2025,0.78,NaN,0.78,NaN,0.78,NaN,0.79,NaN,0.79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
table_18 = pd.read_excel("datas/Statistical Tables on June 2025 CPI for All Income Households.xlsx", sheet_name="table 18", skiprows=3)

In [40]:
table_18

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jan,NaN,Feb,NaN,Mar,NaN,Apr,NaN,May,...,NaN,Sep,NaN,Oct,NaN,Nov,NaN,Dec,NaN,Ave
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1994,3.09,NaN,3.05,NaN,3.06,NaN,3.05,NaN,3.03,...,NaN,2.97,NaN,2.97,NaN,2.97,NaN,2.96,NaN,3.01
4,1995,2.91,NaN,2.89,NaN,2.88,NaN,2.87,NaN,2.86,...,NaN,2.75,NaN,2.74,NaN,2.74,NaN,2.74,NaN,2.82
5,1996,2.66,NaN,2.64,NaN,2.64,NaN,2.63,NaN,2.62,...,NaN,2.58,NaN,2.57,NaN,2.57,NaN,2.55,NaN,2.6
6,1997,2.52,NaN,2.51,NaN,2.5,NaN,2.5,NaN,2.49,...,NaN,2.44,NaN,2.43,NaN,2.41,NaN,2.4,NaN,2.46
7,1998,2.37,NaN,2.33,NaN,2.31,NaN,2.3,NaN,2.27,...,NaN,2.21,NaN,2.21,NaN,2.18,NaN,2.18,NaN,2.25
8,1999,2.14,NaN,2.13,NaN,2.14,NaN,2.14,NaN,2.14,...,NaN,2.11,NaN,2.1,NaN,2.1,NaN,2.1,NaN,2.12
9,2000,2.03,NaN,2.02,NaN,2.02,NaN,2.02,NaN,2.01,...,NaN,1.98,NaN,1.97,NaN,1.94,NaN,1.93,NaN,1.99
10,2001,1.91,NaN,1.91,NaN,1.91,NaN,1.91,NaN,1.91,...,NaN,1.87,NaN,1.87,NaN,1.87,NaN,1.86,NaN,1.89
11,2002,1.85,NaN,1.86,NaN,1.85,NaN,1.85,NaN,1.85,...,NaN,1.83,NaN,1.83,NaN,1.83,NaN,1.82,NaN,1.84
12,2003,1.82,NaN,1.81,NaN,1.81,NaN,1.81,NaN,1.81,...,NaN,1.79,NaN,1.79,NaN,1.78,NaN,1.78,NaN,1.8
13,2004,1.77,NaN,1.76,NaN,1.76,NaN,1.75,NaN,1.74,...,NaN,1.68,NaN,1.68,NaN,1.67,NaN,1.66,NaN,1.72
14,2005,1.65,NaN,1.64,NaN,1.64,NaN,1.63,NaN,1.63,...,NaN,1.59,NaN,1.58,NaN,1.57,NaN,1.57,NaN,1.61
15,2006,1.56,NaN,1.54,NaN,1.54,NaN,1.54,NaN,1.53,...,NaN,1.52,NaN,1.51,NaN,1.51,NaN,1.51,NaN,1.53
16,2007,1.5,NaN,1.5,NaN,1.5,NaN,1.5,NaN,1.49,...,NaN,1.47,NaN,1.47,NaN,1.46,NaN,1.45,NaN,1.48
17,2008,1.43,NaN,1.43,NaN,1.42,NaN,1.4,NaN,1.38,...,NaN,1.34,NaN,1.34,NaN,1.34,NaN,1.35,NaN,1.37
18,2009,1.34,NaN,1.33,NaN,1.33,NaN,1.32,NaN,1.32,...,NaN,1.31,NaN,1.3,NaN,1.3,NaN,1.29,NaN,1.31
19,2010,1.29,NaN,1.28,NaN,1.28,NaN,1.27,NaN,1.27,...,NaN,1.26,NaN,1.26,NaN,1.25,NaN,1.25,NaN,1.27
20,2011,1.24,NaN,1.22,NaN,1.22,NaN,1.22,NaN,1.21,...,NaN,1.2,NaN,1.2,NaN,1.19,NaN,1.2,NaN,1.21
21,2012,1.19,NaN,1.19,NaN,1.19,NaN,1.18,NaN,1.18,...,NaN,1.16,NaN,1.16,NaN,1.16,NaN,1.16,NaN,1.17
22,2013,1.16,NaN,1.15,NaN,1.15,NaN,1.15,NaN,1.15,...,NaN,1.14,NaN,1.13,NaN,1.13,NaN,1.12,NaN,1.14
23,2014,1.12,NaN,1.11,NaN,1.12,NaN,1.11,NaN,1.11,...,NaN,1.09,NaN,1.09,NaN,1.1,NaN,1.1,NaN,1.1
24,2015,1.1,NaN,1.1,NaN,1.1,NaN,1.1,NaN,1.1,...,NaN,1.1,NaN,1.1,NaN,1.09,NaN,1.09,NaN,1.1
25,2016,1.09,NaN,1.09,NaN,1.09,NaN,1.09,NaN,1.09,...,NaN,1.08,NaN,1.08,NaN,1.07,NaN,1.07,NaN,1.08
26,2017,1.06,NaN,1.06,NaN,1.06,NaN,1.06,NaN,1.06,...,NaN,1.05,NaN,1.04,NaN,1.04,NaN,1.04,NaN,1.05
27,2018,1.03,NaN,1.02,NaN,1.02,NaN,1.01,NaN,1.01,...,NaN,0.98,NaN,0.98,NaN,0.98,NaN,0.99,NaN,1
28,2019,0.99,NaN,0.98,NaN,0.98,NaN,0.98,NaN,0.98,...,NaN,0.97,NaN,0.97,NaN,0.97,NaN,0.96,NaN,0.98
29,2020,0.96,NaN,0.96,NaN,0.96,NaN,0.96,NaN,0.96,...,NaN,0.95,NaN,0.95,NaN,0.94,NaN,0.93,NaN,0.95
30,2021,0.92,NaN,0.92,NaN,0.92,NaN,0.93,NaN,0.93,...,NaN,0.91,NaN,0.91,NaN,0.91,NaN,0.9,NaN,0.92
31,2022,0.9,NaN,0.89,NaN,0.89,NaN,0.88,NaN,0.88,...,NaN,0.86,NaN,0.85,NaN,0.84,NaN,0.84,NaN,0.87
32,2023,0.82,NaN,0.82,NaN,0.83,NaN,0.83,NaN,0.83,...,NaN,0.81,NaN,0.81,NaN,0.81,NaN,0.81,NaN,0.82
33,2024,0.8,NaN,0.8,NaN,0.8,NaN,0.8,NaN,0.8,...,NaN,0.79,NaN,0.79,NaN,0.79,NaN,0.78,NaN,0.79
34,2025,0.78,NaN,0.78,NaN,0.78,NaN,0.79,NaN,0.79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
threshold = len(table_18) * 0.5  # 50% threshold
table_18 = table_18.dropna(axis=1, thresh=threshold)

table_18

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,Unnamed: 19,Unnamed: 21,Unnamed: 23,Unnamed: 25
0,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1994,3.09,3.05,3.06,3.05,3.03,3.02,3,2.98,2.97,2.97,2.97,2.96,3.01
4,1995,2.91,2.89,2.88,2.87,2.86,2.84,2.82,2.79,2.75,2.74,2.74,2.74,2.82
5,1996,2.66,2.64,2.64,2.63,2.62,2.6,2.6,2.58,2.58,2.57,2.57,2.55,2.6
6,1997,2.52,2.51,2.5,2.5,2.49,2.47,2.46,2.45,2.44,2.43,2.41,2.4,2.46
7,1998,2.37,2.33,2.31,2.3,2.27,2.24,2.23,2.22,2.21,2.21,2.18,2.18,2.25
8,1999,2.14,2.13,2.14,2.14,2.14,2.13,2.12,2.12,2.11,2.1,2.1,2.1,2.12
9,2000,2.03,2.02,2.02,2.02,2.01,2,1.99,1.98,1.98,1.97,1.94,1.93,1.99
10,2001,1.91,1.91,1.91,1.91,1.91,1.89,1.88,1.88,1.87,1.87,1.87,1.86,1.89
11,2002,1.85,1.86,1.85,1.85,1.85,1.84,1.83,1.83,1.83,1.83,1.83,1.82,1.84
12,2003,1.82,1.81,1.81,1.81,1.81,1.79,1.79,1.79,1.79,1.79,1.78,1.78,1.8
13,2004,1.77,1.76,1.76,1.75,1.74,1.72,1.7,1.69,1.68,1.68,1.67,1.66,1.72
14,2005,1.65,1.64,1.64,1.63,1.63,1.61,1.6,1.59,1.59,1.58,1.57,1.57,1.61
15,2006,1.56,1.54,1.54,1.54,1.53,1.52,1.52,1.52,1.52,1.51,1.51,1.51,1.53
16,2007,1.5,1.5,1.5,1.5,1.49,1.49,1.48,1.48,1.47,1.47,1.46,1.45,1.48
17,2008,1.43,1.43,1.42,1.4,1.38,1.36,1.34,1.34,1.34,1.34,1.34,1.35,1.37
18,2009,1.34,1.33,1.33,1.32,1.32,1.32,1.31,1.31,1.31,1.3,1.3,1.29,1.31
19,2010,1.29,1.28,1.28,1.27,1.27,1.27,1.27,1.26,1.26,1.26,1.25,1.25,1.27
20,2011,1.24,1.22,1.22,1.22,1.21,1.21,1.21,1.2,1.2,1.2,1.19,1.2,1.21
21,2012,1.19,1.19,1.19,1.18,1.18,1.17,1.17,1.16,1.16,1.16,1.16,1.16,1.17
22,2013,1.16,1.15,1.15,1.15,1.15,1.15,1.14,1.14,1.14,1.13,1.13,1.12,1.14
23,2014,1.12,1.11,1.12,1.11,1.11,1.1,1.1,1.1,1.09,1.09,1.1,1.1,1.1
24,2015,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.09,1.09,1.1
25,2016,1.09,1.09,1.09,1.09,1.09,1.08,1.08,1.08,1.08,1.08,1.07,1.07,1.08
26,2017,1.06,1.06,1.06,1.06,1.06,1.06,1.06,1.05,1.05,1.04,1.04,1.04,1.05
27,2018,1.03,1.02,1.02,1.01,1.01,1.01,1,0.99,0.98,0.98,0.98,0.99,1
28,2019,0.99,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.97,0.97,0.97,0.96,0.98
29,2020,0.96,0.96,0.96,0.96,0.96,0.96,0.95,0.95,0.95,0.95,0.94,0.93,0.95
30,2021,0.92,0.92,0.92,0.93,0.93,0.92,0.92,0.91,0.91,0.91,0.91,0.9,0.92
31,2022,0.9,0.89,0.89,0.88,0.88,0.87,0.86,0.86,0.86,0.85,0.84,0.84,0.87
32,2023,0.82,0.82,0.83,0.83,0.83,0.83,0.83,0.82,0.81,0.81,0.81,0.81,0.82
33,2024,0.8,0.8,0.8,0.8,0.8,0.8,0.79,0.79,0.79,0.79,0.79,0.78,0.79
34,2025,0.78,0.78,0.78,0.79,0.79,0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
print(table_18.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 3', 'Unnamed: 5', 'Unnamed: 7',
       'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 13', 'Unnamed: 15',
       'Unnamed: 17', 'Unnamed: 19', 'Unnamed: 21', 'Unnamed: 23',
       'Unnamed: 25'],
      dtype='object')

In [43]:
table_18

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,Unnamed: 19,Unnamed: 21,Unnamed: 23,Unnamed: 25
0,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1994,3.09,3.05,3.06,3.05,3.03,3.02,3,2.98,2.97,2.97,2.97,2.96,3.01
4,1995,2.91,2.89,2.88,2.87,2.86,2.84,2.82,2.79,2.75,2.74,2.74,2.74,2.82
5,1996,2.66,2.64,2.64,2.63,2.62,2.6,2.6,2.58,2.58,2.57,2.57,2.55,2.6
6,1997,2.52,2.51,2.5,2.5,2.49,2.47,2.46,2.45,2.44,2.43,2.41,2.4,2.46
7,1998,2.37,2.33,2.31,2.3,2.27,2.24,2.23,2.22,2.21,2.21,2.18,2.18,2.25
8,1999,2.14,2.13,2.14,2.14,2.14,2.13,2.12,2.12,2.11,2.1,2.1,2.1,2.12
9,2000,2.03,2.02,2.02,2.02,2.01,2,1.99,1.98,1.98,1.97,1.94,1.93,1.99
10,2001,1.91,1.91,1.91,1.91,1.91,1.89,1.88,1.88,1.87,1.87,1.87,1.86,1.89
11,2002,1.85,1.86,1.85,1.85,1.85,1.84,1.83,1.83,1.83,1.83,1.83,1.82,1.84
12,2003,1.82,1.81,1.81,1.81,1.81,1.79,1.79,1.79,1.79,1.79,1.78,1.78,1.8
13,2004,1.77,1.76,1.76,1.75,1.74,1.72,1.7,1.69,1.68,1.68,1.67,1.66,1.72
14,2005,1.65,1.64,1.64,1.63,1.63,1.61,1.6,1.59,1.59,1.58,1.57,1.57,1.61
15,2006,1.56,1.54,1.54,1.54,1.53,1.52,1.52,1.52,1.52,1.51,1.51,1.51,1.53
16,2007,1.5,1.5,1.5,1.5,1.49,1.49,1.48,1.48,1.47,1.47,1.46,1.45,1.48
17,2008,1.43,1.43,1.42,1.4,1.38,1.36,1.34,1.34,1.34,1.34,1.34,1.35,1.37
18,2009,1.34,1.33,1.33,1.32,1.32,1.32,1.31,1.31,1.31,1.3,1.3,1.29,1.31
19,2010,1.29,1.28,1.28,1.27,1.27,1.27,1.27,1.26,1.26,1.26,1.25,1.25,1.27
20,2011,1.24,1.22,1.22,1.22,1.21,1.21,1.21,1.2,1.2,1.2,1.19,1.2,1.21
21,2012,1.19,1.19,1.19,1.18,1.18,1.17,1.17,1.16,1.16,1.16,1.16,1.16,1.17
22,2013,1.16,1.15,1.15,1.15,1.15,1.15,1.14,1.14,1.14,1.13,1.13,1.12,1.14
23,2014,1.12,1.11,1.12,1.11,1.11,1.1,1.1,1.1,1.09,1.09,1.1,1.1,1.1
24,2015,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.09,1.09,1.1
25,2016,1.09,1.09,1.09,1.09,1.09,1.08,1.08,1.08,1.08,1.08,1.07,1.07,1.08
26,2017,1.06,1.06,1.06,1.06,1.06,1.06,1.06,1.05,1.05,1.04,1.04,1.04,1.05
27,2018,1.03,1.02,1.02,1.01,1.01,1.01,1,0.99,0.98,0.98,0.98,0.99,1
28,2019,0.99,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.97,0.97,0.97,0.96,0.98
29,2020,0.96,0.96,0.96,0.96,0.96,0.96,0.95,0.95,0.95,0.95,0.94,0.93,0.95
30,2021,0.92,0.92,0.92,0.93,0.93,0.92,0.92,0.91,0.91,0.91,0.91,0.9,0.92
31,2022,0.9,0.89,0.89,0.88,0.88,0.87,0.86,0.86,0.86,0.85,0.84,0.84,0.87
32,2023,0.82,0.82,0.83,0.83,0.83,0.83,0.83,0.82,0.81,0.81,0.81,0.81,0.82
33,2024,0.8,0.8,0.8,0.8,0.8,0.8,0.79,0.79,0.79,0.79,0.79,0.78,0.79
34,2025,0.78,0.78,0.78,0.79,0.79,0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# Example: Assign a new list of column names

table_18.columns = ["Year", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Ave"]

print(table_18.columns)

Index(['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec', 'Ave'],
      dtype='object')

In [45]:
table_18

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
0,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1994,3.09,3.05,3.06,3.05,3.03,3.02,3,2.98,2.97,2.97,2.97,2.96,3.01
4,1995,2.91,2.89,2.88,2.87,2.86,2.84,2.82,2.79,2.75,2.74,2.74,2.74,2.82
5,1996,2.66,2.64,2.64,2.63,2.62,2.6,2.6,2.58,2.58,2.57,2.57,2.55,2.6
6,1997,2.52,2.51,2.5,2.5,2.49,2.47,2.46,2.45,2.44,2.43,2.41,2.4,2.46
7,1998,2.37,2.33,2.31,2.3,2.27,2.24,2.23,2.22,2.21,2.21,2.18,2.18,2.25
8,1999,2.14,2.13,2.14,2.14,2.14,2.13,2.12,2.12,2.11,2.1,2.1,2.1,2.12
9,2000,2.03,2.02,2.02,2.02,2.01,2,1.99,1.98,1.98,1.97,1.94,1.93,1.99
10,2001,1.91,1.91,1.91,1.91,1.91,1.89,1.88,1.88,1.87,1.87,1.87,1.86,1.89
11,2002,1.85,1.86,1.85,1.85,1.85,1.84,1.83,1.83,1.83,1.83,1.83,1.82,1.84
12,2003,1.82,1.81,1.81,1.81,1.81,1.79,1.79,1.79,1.79,1.79,1.78,1.78,1.8
13,2004,1.77,1.76,1.76,1.75,1.74,1.72,1.7,1.69,1.68,1.68,1.67,1.66,1.72
14,2005,1.65,1.64,1.64,1.63,1.63,1.61,1.6,1.59,1.59,1.58,1.57,1.57,1.61
15,2006,1.56,1.54,1.54,1.54,1.53,1.52,1.52,1.52,1.52,1.51,1.51,1.51,1.53
16,2007,1.5,1.5,1.5,1.5,1.49,1.49,1.48,1.48,1.47,1.47,1.46,1.45,1.48
17,2008,1.43,1.43,1.42,1.4,1.38,1.36,1.34,1.34,1.34,1.34,1.34,1.35,1.37
18,2009,1.34,1.33,1.33,1.32,1.32,1.32,1.31,1.31,1.31,1.3,1.3,1.29,1.31
19,2010,1.29,1.28,1.28,1.27,1.27,1.27,1.27,1.26,1.26,1.26,1.25,1.25,1.27
20,2011,1.24,1.22,1.22,1.22,1.21,1.21,1.21,1.2,1.2,1.2,1.19,1.2,1.21
21,2012,1.19,1.19,1.19,1.18,1.18,1.17,1.17,1.16,1.16,1.16,1.16,1.16,1.17
22,2013,1.16,1.15,1.15,1.15,1.15,1.15,1.14,1.14,1.14,1.13,1.13,1.12,1.14
23,2014,1.12,1.11,1.12,1.11,1.11,1.1,1.1,1.1,1.09,1.09,1.1,1.1,1.1
24,2015,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.09,1.09,1.1
25,2016,1.09,1.09,1.09,1.09,1.09,1.08,1.08,1.08,1.08,1.08,1.07,1.07,1.08
26,2017,1.06,1.06,1.06,1.06,1.06,1.06,1.06,1.05,1.05,1.04,1.04,1.04,1.05
27,2018,1.03,1.02,1.02,1.01,1.01,1.01,1,0.99,0.98,0.98,0.98,0.99,1
28,2019,0.99,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.97,0.97,0.97,0.96,0.98
29,2020,0.96,0.96,0.96,0.96,0.96,0.96,0.95,0.95,0.95,0.95,0.94,0.93,0.95
30,2021,0.92,0.92,0.92,0.93,0.93,0.92,0.92,0.91,0.91,0.91,0.91,0.9,0.92
31,2022,0.9,0.89,0.89,0.88,0.88,0.87,0.86,0.86,0.86,0.85,0.84,0.84,0.87
32,2023,0.82,0.82,0.83,0.83,0.83,0.83,0.83,0.82,0.81,0.81,0.81,0.81,0.82
33,2024,0.8,0.8,0.8,0.8,0.8,0.8,0.79,0.79,0.79,0.79,0.79,0.78,0.79
34,2025,0.78,0.78,0.78,0.79,0.79,0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
table_18 = table_18.iloc[3:].reset_index(drop=True)

In [47]:
table_18 = table_18.drop("Ave", axis=1)

In [48]:
table_18.to_csv("table_18_cleaned.csv", index=False)

table_18

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1994,3.09,3.05,3.06,3.05,3.03,3.02,3,2.98,2.97,2.97,2.97,2.96
1,1995,2.91,2.89,2.88,2.87,2.86,2.84,2.82,2.79,2.75,2.74,2.74,2.74
2,1996,2.66,2.64,2.64,2.63,2.62,2.6,2.6,2.58,2.58,2.57,2.57,2.55
3,1997,2.52,2.51,2.5,2.5,2.49,2.47,2.46,2.45,2.44,2.43,2.41,2.4
4,1998,2.37,2.33,2.31,2.3,2.27,2.24,2.23,2.22,2.21,2.21,2.18,2.18
5,1999,2.14,2.13,2.14,2.14,2.14,2.13,2.12,2.12,2.11,2.1,2.1,2.1
6,2000,2.03,2.02,2.02,2.02,2.01,2,1.99,1.98,1.98,1.97,1.94,1.93
7,2001,1.91,1.91,1.91,1.91,1.91,1.89,1.88,1.88,1.87,1.87,1.87,1.86
8,2002,1.85,1.86,1.85,1.85,1.85,1.84,1.83,1.83,1.83,1.83,1.83,1.82
9,2003,1.82,1.81,1.81,1.81,1.81,1.79,1.79,1.79,1.79,1.79,1.78,1.78
10,2004,1.77,1.76,1.76,1.75,1.74,1.72,1.7,1.69,1.68,1.68,1.67,1.66
11,2005,1.65,1.64,1.64,1.63,1.63,1.61,1.6,1.59,1.59,1.58,1.57,1.57
12,2006,1.56,1.54,1.54,1.54,1.53,1.52,1.52,1.52,1.52,1.51,1.51,1.51
13,2007,1.5,1.5,1.5,1.5,1.49,1.49,1.48,1.48,1.47,1.47,1.46,1.45
14,2008,1.43,1.43,1.42,1.4,1.38,1.36,1.34,1.34,1.34,1.34,1.34,1.35
15,2009,1.34,1.33,1.33,1.32,1.32,1.32,1.31,1.31,1.31,1.3,1.3,1.29
16,2010,1.29,1.28,1.28,1.27,1.27,1.27,1.27,1.26,1.26,1.26,1.25,1.25
17,2011,1.24,1.22,1.22,1.22,1.21,1.21,1.21,1.2,1.2,1.2,1.19,1.2
18,2012,1.19,1.19,1.19,1.18,1.18,1.17,1.17,1.16,1.16,1.16,1.16,1.16
19,2013,1.16,1.15,1.15,1.15,1.15,1.15,1.14,1.14,1.14,1.13,1.13,1.12
20,2014,1.12,1.11,1.12,1.11,1.11,1.1,1.1,1.1,1.09,1.09,1.1,1.1
21,2015,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.09,1.09
22,2016,1.09,1.09,1.09,1.09,1.09,1.08,1.08,1.08,1.08,1.08,1.07,1.07
23,2017,1.06,1.06,1.06,1.06,1.06,1.06,1.06,1.05,1.05,1.04,1.04,1.04
24,2018,1.03,1.02,1.02,1.01,1.01,1.01,1,0.99,0.98,0.98,0.98,0.99
25,2019,0.99,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.97,0.97,0.97,0.96
26,2020,0.96,0.96,0.96,0.96,0.96,0.96,0.95,0.95,0.95,0.95,0.94,0.93
27,2021,0.92,0.92,0.92,0.93,0.93,0.92,0.92,0.91,0.91,0.91,0.91,0.9
28,2022,0.9,0.89,0.89,0.88,0.88,0.87,0.86,0.86,0.86,0.85,0.84,0.84
29,2023,0.82,0.82,0.83,0.83,0.83,0.83,0.83,0.82,0.81,0.81,0.81,0.81
30,2024,0.8,0.8,0.8,0.8,0.8,0.8,0.79,0.79,0.79,0.79,0.79,0.78
31,2025,0.78,0.78,0.78,0.79,0.79,0.78,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"Source: Philippine Statistics Authority, Retai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
table_18 = table_18.iloc[:-3].reset_index(drop=True)

In [50]:
table_18.to_csv("table_18_cleaned.csv", index=False)

In [51]:
table_18

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1994,3.09,3.05,3.06,3.05,3.03,3.02,3,2.98,2.97,2.97,2.97,2.96
1,1995,2.91,2.89,2.88,2.87,2.86,2.84,2.82,2.79,2.75,2.74,2.74,2.74
2,1996,2.66,2.64,2.64,2.63,2.62,2.6,2.6,2.58,2.58,2.57,2.57,2.55
3,1997,2.52,2.51,2.5,2.5,2.49,2.47,2.46,2.45,2.44,2.43,2.41,2.4
4,1998,2.37,2.33,2.31,2.3,2.27,2.24,2.23,2.22,2.21,2.21,2.18,2.18
5,1999,2.14,2.13,2.14,2.14,2.14,2.13,2.12,2.12,2.11,2.1,2.1,2.1
6,2000,2.03,2.02,2.02,2.02,2.01,2,1.99,1.98,1.98,1.97,1.94,1.93
7,2001,1.91,1.91,1.91,1.91,1.91,1.89,1.88,1.88,1.87,1.87,1.87,1.86
8,2002,1.85,1.86,1.85,1.85,1.85,1.84,1.83,1.83,1.83,1.83,1.83,1.82
9,2003,1.82,1.81,1.81,1.81,1.81,1.79,1.79,1.79,1.79,1.79,1.78,1.78
10,2004,1.77,1.76,1.76,1.75,1.74,1.72,1.7,1.69,1.68,1.68,1.67,1.66
11,2005,1.65,1.64,1.64,1.63,1.63,1.61,1.6,1.59,1.59,1.58,1.57,1.57
12,2006,1.56,1.54,1.54,1.54,1.53,1.52,1.52,1.52,1.52,1.51,1.51,1.51
13,2007,1.5,1.5,1.5,1.5,1.49,1.49,1.48,1.48,1.47,1.47,1.46,1.45
14,2008,1.43,1.43,1.42,1.4,1.38,1.36,1.34,1.34,1.34,1.34,1.34,1.35
15,2009,1.34,1.33,1.33,1.32,1.32,1.32,1.31,1.31,1.31,1.3,1.3,1.29
16,2010,1.29,1.28,1.28,1.27,1.27,1.27,1.27,1.26,1.26,1.26,1.25,1.25
17,2011,1.24,1.22,1.22,1.22,1.21,1.21,1.21,1.2,1.2,1.2,1.19,1.2
18,2012,1.19,1.19,1.19,1.18,1.18,1.17,1.17,1.16,1.16,1.16,1.16,1.16
19,2013,1.16,1.15,1.15,1.15,1.15,1.15,1.14,1.14,1.14,1.13,1.13,1.12
20,2014,1.12,1.11,1.12,1.11,1.11,1.1,1.1,1.1,1.09,1.09,1.1,1.1
21,2015,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.09,1.09
22,2016,1.09,1.09,1.09,1.09,1.09,1.08,1.08,1.08,1.08,1.08,1.07,1.07
23,2017,1.06,1.06,1.06,1.06,1.06,1.06,1.06,1.05,1.05,1.04,1.04,1.04
24,2018,1.03,1.02,1.02,1.01,1.01,1.01,1,0.99,0.98,0.98,0.98,0.99
25,2019,0.99,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.97,0.97,0.97,0.96
26,2020,0.96,0.96,0.96,0.96,0.96,0.96,0.95,0.95,0.95,0.95,0.94,0.93
27,2021,0.92,0.92,0.92,0.93,0.93,0.92,0.92,0.91,0.91,0.91,0.91,0.9
28,2022,0.9,0.89,0.89,0.88,0.88,0.87,0.86,0.86,0.86,0.85,0.84,0.84
29,2023,0.82,0.82,0.83,0.83,0.83,0.83,0.83,0.82,0.81,0.81,0.81,0.81
30,2024,0.8,0.8,0.8,0.8,0.8,0.8,0.79,0.79,0.79,0.79,0.79,0.78
31,2025,0.78,0.78,0.78,0.79,0.79,0.78,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
import pandas as pd
import plotly.graph_objects as go

# Load your CSV
# ...existing code...
df = pd.read_csv("datas/merged_output_w_price.csv")
df2 = pd.read_csv("datas/RicePriceHistory_Retail.csv")

df.rename(columns={'Rice Price': 'Rice Price - Farmgate'}, inplace=True)

# Merge df2's rice price column into df based on 'Year'
df = df.merge(df2[['Year', 'Rice Price - Regular']], on='Year', how='left')

# Now df has a new 'Rice Price' column from df2
df.head()
# ...existing code...

df.to_csv('merged_output_w_price.csv', index=False)